all_joints: # change this
- - 0
- - 1
- - 2
- - 3
- - 4
- - 5
- - 6
- - 7
- - 8
- - 9
- - 10
- - 11
- - 12
- - 13
all_joints_names: # change this
- yaw_1_front
- yaw_2_front
- pitch_1_front
- pitch_2_front
- pitch_3_front
- roll_1_front
- roll_2_front
- yaw_1_back
- yaw_2_back
- pitch_1_back
- pitch_2_back
- pitch_3_back
- roll_1_back
- roll_2_back
batch_size: 1
#bottomheight: 400
#crop: true
#cropratio: 0.4
dataset: training-datasets/iteration-0/UnaugmentedDataSet_tool_trackingSep23/tool_tracking_JP99shuffle1.mat
dataset_type: default
display_iters: 1000
#global_scale: 0.8
init_weights: /home/jingpei/anaconda3/envs/DLC-GPU/lib/python3.7/site-packages/deeplabcut/pose_estimation_tensorflow/models/pretrained/resnet_v1_50.ckpt
intermediate_supervision: false
intermediate_supervision_layer: 12
leftwidth: 400
location_refinement: true
locref_huber_loss: true
locref_loss_weight: 0.05
locref_stdev: 7.2801
max_input_size: 1500
metadataset: training-datasets/iteration-0/UnaugmentedDataSet_tool_trackingSep23/Documentation_data-tool_tracking_99shuffle1.pickle
min_input_size: 64
minsize: 100
mirror: false
multi_step:
- - 0.005
  - 10000
- - 0.02
  - 430000
- - 0.002
  - 730000
- - 0.001
  - 1030000
net_type: resnet_50
num_joints: 14  # change this
pos_dist_thresh: 17
project_path: /home/jingpei/Desktop/rope_data/tool_tracking-JP-2021-09-23
rightwidth: 400
save_iters: 10000
scale_jitter_lo: 0.5
scale_jitter_up: 1.25
topheight: 400
